#!/usr/bin/env bash
set -euo pipefail
#
# install.sh — configure this machine's agent-pages gallery.
#
# agent-pages now ships as a Claude Code *plugin* (skills + commands + hooks).
# The plugin is installed once via `/plugin` (see the printed instructions);
# this script only does the gallery-local, deterministic setup:
#
#   1. writes your runtime config -> ~/.claude/agent-pages/config.env
#      (gallery path = this repo clone, remote/branch = this repo's origin)
#   2. seeds gallery metadata      -> gallery.json (title + category options)
#   3. prints the /plugin commands to install the capability
#
# It is idempotent and local-only — it never pushes and never edits settings.json.
#
# Run it from inside your gallery clone (the fork of this repo):
#   ./scripts/install.sh [--gallery PATH] [--site URL] [--name "Agent <Pages/>"] [--force]

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(git -C "$here" rev-parse --show-toplevel 2>/dev/null || dirname "$here")"

claude_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
cfg_dir="$claude_dir/agent-pages"
cfg_file="$cfg_dir/config.env"

gallery="$repo_root"
site_url=""
gallery_name=""
force=0
while [ $# -gt 0 ]; do
  case "$1" in
    --gallery) gallery="${2:?}"; shift 2 ;;
    --site)    site_url="${2:?}"; shift 2 ;;
    --name)    gallery_name="${2:?}"; shift 2 ;;
    --force)   force=1; shift ;;
    -h|--help) sed -n '2,21p' "$0"; exit 0 ;;
    *) echo "install: unknown argument: $1" >&2; exit 1 ;;
  esac
done

say() { printf '  %s\n' "$*"; }
echo "agent-pages install"

default_gallery_name="Agent <Pages/>"
if [ -z "$gallery_name" ]; then
  if [ -t 0 ]; then
    printf 'Gallery title [%s]: ' "$default_gallery_name"
    IFS= read -r gallery_name || gallery_name=""
    gallery_name="${gallery_name:-$default_gallery_name}"
  else
    gallery_name="$default_gallery_name"
  fi
fi

# --- 1. config ---
mkdir -p "$cfg_dir"
remote="$(git -C "$repo_root" remote get-url origin 2>/dev/null || echo '')"
branch="$(git -C "$repo_root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'main')"
if [ -f "$cfg_file" ] && [ "$force" -ne 1 ]; then
  say "config  -> $cfg_file (kept; pass --force to overwrite)"
else
  cat > "$cfg_file" <<EOF
# agent-pages configuration (generated by install.sh; edit freely)
AGENT_PAGES_GALLERY_PATH="$gallery"
AGENT_PAGES_REMOTE="$remote"
AGENT_PAGES_BRANCH="$branch"
AGENT_PAGES_SITE_BASE_URL="$site_url"
AGENT_PAGES_GALLERY_NAME="$gallery_name"
AGENT_PAGES_DEFAULT_PROJECT=""
EOF
  say "config  -> $cfg_file"
fi

# --- 2. gallery metadata ---
gallery_json="$gallery/gallery.json"
if [ -f "$gallery_json" ]; then
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$gallery_json" "$gallery_name" <<'PY'
import json
import sys

DEFAULT_CATEGORIES = [
    {"slug": "engineering", "label": "Engineering"},
    {"slug": "product", "label": "Product"},
    {"slug": "design", "label": "Design"},
    {"slug": "research", "label": "Research"},
    {"slug": "learning", "label": "Learning"},
    {"slug": "operations", "label": "Operations"},
    {"slug": "other", "label": "Other"},
]

path, title = sys.argv[1:3]
with open(path, "r", encoding="utf-8") as fh:
    data = json.load(fh)
site = data.setdefault("site", {})
data.setdefault("$schema", "./gallery.schema.json")
data.setdefault("categories", DEFAULT_CATEGORIES)
site["title"] = title
site.pop("description", None)
with open(path, "w", encoding="utf-8") as fh:
    json.dump(data, fh, ensure_ascii=False, indent=2)
    fh.write("\n")
PY
    say "gallery -> $gallery_json (title: $gallery_name)"
  else
    say "gallery -> python3 not found; kept $gallery_json unchanged"
  fi
fi

# --- 3. plugin install instructions ---
cat <<EOF

Done. The gallery is configured. Now install the plugin (one time) inside Claude Code:

  /plugin marketplace add $gallery
  /plugin install agent-pages@agent-pages

The plugin ships the skills (agent-pages workflow + use-agent-pages bootstrap)
and a SessionStart hook that injects the use-agent-pages doctrine each session.
There is no settings.json hook to install anymore.

Next:
  - Run the two /plugin commands above (or restart Claude Code afterwards).
  - Enable GitHub Pages on your fork (Settings > Pages > deploy from $branch).
  - Optionally set a domain: cp CNAME.example CNAME && edit it.
  - Try it:  /agent-pages <topic>
EOF
