#!/usr/bin/env bash
set -euo pipefail
#
# install.sh — make this machine capable of agent-pages.
#
# What it does (idempotent, local-only — never pushes):
#   1. installs the skill        -> ~/.claude/skills/agent-pages/SKILL.md
#   2. writes your config        -> ~/.claude/agent-pages/config.env
#      (gallery path = this repo clone, remote/branch = this repo's origin)
#   3. (optional) installs the   -> ~/.claude/settings.json
#      "/agent-pages" hint hook       UserPromptSubmit
#
# Run it from inside your gallery clone (the fork of this repo):
#   ./scripts/install.sh [--gallery PATH] [--site URL] [--name "Agent <Pages/>"] [--with-hook|--no-hook] [--force]

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(git -C "$here" rev-parse --show-toplevel 2>/dev/null || dirname "$here")"

claude_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
skills_dst="$claude_dir/skills/agent-pages"
cfg_dir="$claude_dir/agent-pages"
cfg_file="$cfg_dir/config.env"
settings_file="$claude_dir/settings.json"

gallery="$repo_root"
site_url=""
gallery_name=""
with_hook=""
force=0
while [ $# -gt 0 ]; do
  case "$1" in
    --gallery) gallery="${2:?}"; shift 2 ;;
    --site)    site_url="${2:?}"; shift 2 ;;
    --name)    gallery_name="${2:?}"; shift 2 ;;
    --with-hook) with_hook=1; shift ;;
    --no-hook) with_hook=0; shift ;;
    --force)   force=1; shift ;;
    -h|--help) sed -n '2,14p' "$0"; exit 0 ;;
    *) echo "install: unknown argument: $1" >&2; exit 1 ;;
  esac
done

say() { printf '  %s\n' "$*"; }
echo "agent-pages install"

default_gallery_name="Agent <Pages/>"
if [ -z "$gallery_name" ]; then
  if [ -t 0 ]; then
    printf 'Gallery title [%s]: ' "$default_gallery_name"
    IFS= read -r gallery_name || gallery_name=""
    gallery_name="${gallery_name:-$default_gallery_name}"
  else
    gallery_name="$default_gallery_name"
  fi
fi

if [ -z "$with_hook" ]; then
  with_hook=0
  if [ -t 0 ]; then
    printf 'Install Claude Code /agent-pages recommendation hook? [y/N]: '
    IFS= read -r hook_answer || hook_answer=""
    case "$hook_answer" in
      y|Y|yes|YES|Yes) with_hook=1 ;;
    esac
  fi
fi

# --- 1. skill ---
mkdir -p "$skills_dst"
cp "$repo_root/skills/agent-pages/SKILL.md" "$skills_dst/SKILL.md"
say "skill   -> $skills_dst/SKILL.md"

# --- 2. config ---
mkdir -p "$cfg_dir"
remote="$(git -C "$repo_root" remote get-url origin 2>/dev/null || echo '')"
branch="$(git -C "$repo_root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'main')"
if [ -f "$cfg_file" ] && [ "$force" -ne 1 ]; then
  say "config  -> $cfg_file (kept; pass --force to overwrite)"
else
  cat > "$cfg_file" <<EOF
# agent-pages configuration (generated by install.sh; edit freely)
AGENT_PAGES_GALLERY_PATH="$gallery"
AGENT_PAGES_REMOTE="$remote"
AGENT_PAGES_BRANCH="$branch"
AGENT_PAGES_SITE_BASE_URL="$site_url"
AGENT_PAGES_GALLERY_NAME="$gallery_name"
AGENT_PAGES_DEFAULT_PROJECT=""
EOF
  say "config  -> $cfg_file"
fi

# --- gallery metadata ---
gallery_json="$gallery/gallery.json"
if [ -f "$gallery_json" ]; then
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$gallery_json" "$gallery_name" <<'PY'
import json
import sys

path, title = sys.argv[1:3]
with open(path, "r", encoding="utf-8") as fh:
    data = json.load(fh)
site = data.setdefault("site", {})
data.setdefault("$schema", "./gallery.schema.json")
site["title"] = title
site.pop("description", None)
with open(path, "w", encoding="utf-8") as fh:
    json.dump(data, fh, ensure_ascii=False, indent=2)
    fh.write("\n")
PY
    say "gallery -> $gallery_json (title: $gallery_name)"
  else
    say "gallery -> python3 not found; kept $gallery_json unchanged"
  fi
fi

# --- 3. optional hint hook ---
if [ "$with_hook" -eq 1 ]; then
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$settings_file" <<'PY'
import json, sys, os, shlex
path = sys.argv[1]
hint = (
    "When the user's request would be easier to understand as a self-contained HTML artifact than as a long Markdown response, "
    "briefly offer `/agent-pages <topic>` and ask whether they want that format. Good fits include side-by-side exploration or planning, "
    "annotated code review, design systems or component variants, interactive prototypes, diagrams and research maps, slide/report-style communication, "
    "incident/status/PR write-ups, or small custom review/editing UIs. Do not suggest it for quick answers, short explanations, routine edits, or when the user clearly wants plain text."
)
payload = {"hookSpecificOutput": {"hookEventName": "UserPromptSubmit", "additionalContext": hint}}
cmd = "cat >/dev/null 2>&1; printf '%s' " + shlex.quote(json.dumps(payload, ensure_ascii=False))
data = {}
if os.path.exists(path):
    with open(path) as f:
        try: data = json.load(f)
        except Exception: data = {}
hooks = data.setdefault("hooks", {}).setdefault("UserPromptSubmit", [])
target = {"type": "command", "command": cmd, "timeout": 5,
          "statusMessage": "Inject /agent-pages design hint"}
existing = next(
    (
        h
        for grp in hooks
        for h in grp.get("hooks", [])
        if h.get("type") == "command"
        and "/agent-pages" in h.get("command", "")
        and "additionalContext" in h.get("command", "")
    ),
    None,
)
if existing is None:
    hooks.append({"hooks": [target]})
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print("  hook    -> %s (UserPromptSubmit hint added)" % path)
else:
    existing.update(target)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print("  hook    -> %s (UserPromptSubmit hint updated)" % path)
PY
  else
    say "hook    -> python3 not found; add the snippet from hooks/agent-pages-hint.json to $settings_file manually"
  fi
else
  say "hook    -> skipped (re-run with --with-hook to install the /agent-pages hint)"
fi

cat <<EOF

Done. Next:
  - Restart Claude Code (or /reload) so it picks up the skill.
  - Enable GitHub Pages on your fork (Settings > Pages > deploy from $branch).
  - Optionally set a domain: cp CNAME.example CNAME && edit it.
  - Try it:  /agent-pages <topic>
EOF
