#!/usr/bin/env bash
set -euo pipefail
#
# install.sh — make this machine capable of agent-pages.
#
# What it does (idempotent, local-only — never pushes):
#   1. installs the skill        -> ~/.claude/skills/build-h5/SKILL.md
#   2. writes your config        -> ~/.claude/build-h5/config.env
#      (gallery path = this repo clone, remote/branch = this repo's origin)
#   3. (optional) installs the   -> ~/.claude/settings.json
#      "/build-h5" hint hook       UserPromptSubmit
#
# Run it from inside your gallery clone (the fork of this repo):
#   ./scripts/install.sh [--gallery PATH] [--site URL] [--name "Agent <Pages/>"] [--with-hook] [--force]

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(git -C "$here" rev-parse --show-toplevel 2>/dev/null || dirname "$here")"

claude_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
skills_dst="$claude_dir/skills/build-h5"
cfg_dir="$claude_dir/build-h5"
cfg_file="$cfg_dir/config.env"
settings_file="$claude_dir/settings.json"

gallery="$repo_root"
site_url=""
gallery_name=""
with_hook=0
force=0
while [ $# -gt 0 ]; do
  case "$1" in
    --gallery) gallery="${2:?}"; shift 2 ;;
    --site)    site_url="${2:?}"; shift 2 ;;
    --name)    gallery_name="${2:?}"; shift 2 ;;
    --with-hook) with_hook=1; shift ;;
    --force)   force=1; shift ;;
    -h|--help) sed -n '2,14p' "$0"; exit 0 ;;
    *) echo "install: unknown argument: $1" >&2; exit 1 ;;
  esac
done

say() { printf '  %s\n' "$*"; }
echo "agent-pages install"

default_gallery_name="Agent <Pages/>"
if [ -z "$gallery_name" ]; then
  if [ -t 0 ]; then
    printf 'Gallery title [%s]: ' "$default_gallery_name"
    IFS= read -r gallery_name || gallery_name=""
    gallery_name="${gallery_name:-$default_gallery_name}"
  else
    gallery_name="$default_gallery_name"
  fi
fi

# --- 1. skill ---
mkdir -p "$skills_dst"
cp "$repo_root/skills/build-h5/SKILL.md" "$skills_dst/SKILL.md"
say "skill   -> $skills_dst/SKILL.md"

# --- 2. config ---
mkdir -p "$cfg_dir"
remote="$(git -C "$repo_root" remote get-url origin 2>/dev/null || echo '')"
branch="$(git -C "$repo_root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'main')"
if [ -f "$cfg_file" ] && [ "$force" -ne 1 ]; then
  say "config  -> $cfg_file (kept; pass --force to overwrite)"
else
  cat > "$cfg_file" <<EOF
# agent-pages configuration (generated by install.sh; edit freely)
BUILD_H5_GALLERY_PATH="$gallery"
BUILD_H5_REMOTE="$remote"
BUILD_H5_BRANCH="$branch"
BUILD_H5_SITE_BASE_URL="$site_url"
BUILD_H5_GALLERY_NAME="$gallery_name"
BUILD_H5_DEFAULT_PROJECT=""
EOF
  say "config  -> $cfg_file"
fi

# --- gallery metadata ---
gallery_json="$gallery/gallery.json"
if [ -f "$gallery_json" ]; then
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$gallery_json" "$gallery_name" <<'PY'
import json
import sys

path, title = sys.argv[1:3]
with open(path, "r", encoding="utf-8") as fh:
    data = json.load(fh)
site = data.setdefault("site", {})
site["title"] = title
site.pop("description", None)
with open(path, "w", encoding="utf-8") as fh:
    json.dump(data, fh, ensure_ascii=False, indent=2)
    fh.write("\n")
PY
    say "gallery -> $gallery_json (title: $gallery_name)"
  else
    say "gallery -> python3 not found; kept $gallery_json unchanged"
  fi
fi

# --- 3. optional hint hook ---
hint_cmd='cat >/dev/null 2>&1; printf '"'"'%s'"'"' '"'"'{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"当用户请求详细的设计方案 / 技术方案 / 架构设计，且你打算输出较长篇幅的文字方案时：先用一两句话提示可用 `/build-h5 <主题>` 把方案生成为结构清晰、由浅入深、带图形/表格/动效的独立 HTML 页面，并询问是否采用；除非用户明确要求纯文字，否则优先建议 /build-h5。"}}'"'"''

if [ "$with_hook" -eq 1 ]; then
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$settings_file" "$hint_cmd" <<'PY'
import json, sys, os
path, cmd = sys.argv[1], sys.argv[2]
data = {}
if os.path.exists(path):
    with open(path) as f:
        try: data = json.load(f)
        except Exception: data = {}
hooks = data.setdefault("hooks", {}).setdefault("UserPromptSubmit", [])
exists = any(
    h.get("type") == "command" and "/build-h5" in h.get("command", "") and "additionalContext" in h.get("command", "")
    for grp in hooks for h in grp.get("hooks", [])
)
if not exists:
    hooks.append({"hooks": [{"type": "command", "command": cmd, "timeout": 5,
                             "statusMessage": "Inject /build-h5 design hint"}]})
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print("  hook    -> %s (UserPromptSubmit hint added)" % path)
else:
    print("  hook    -> %s (already present)" % path)
PY
  else
    say "hook    -> python3 not found; add the snippet from hooks/build-h5-hint.json to $settings_file manually"
  fi
else
  say "hook    -> skipped (re-run with --with-hook to install the /build-h5 hint)"
fi

cat <<EOF

Done. Next:
  - Restart Claude Code (or /reload) so it picks up the skill.
  - Enable GitHub Pages on your fork (Settings > Pages > deploy from $branch).
  - Optionally set a domain: cp CNAME.example CNAME && edit it.
  - Try it:  /build-h5 <topic>
EOF
