#!/usr/bin/env bash
set -euo pipefail
#
# setup.sh — one-time scaffold for an agent-pages site.
#
# agent-pages ships as a Claude Code *plugin* installed from a marketplace. This
# script runs once (the skill calls it on first use) to:
#
#   1. scaffold the site at AGENT_PAGES_PATH from the plugin's templates/
#      (index.html + data.json + data.schema.json + CNAME.example), git-init it
#   2. seed data.json metadata (title + category options)
#   3. write config + state -> CLAUDE_PLUGIN_DATA/config.env (survives updates)
#
# It is idempotent and local-only — it never pushes. Existing files are kept
# unless --force is given (so re-running never clobbers your pages or data.json).
#
# Usage (paths are normally the plugin vars, substituted by the skill):
#   setup.sh --config <CLAUDE_PLUGIN_DATA>/config.env \
#            [--templates <CLAUDE_PLUGIN_ROOT>/templates] \
#            [--path PATH] [--name "Agent <Pages/>"] [--site URL] \
#            [--repo GIT_URL] [--branch main] [--force]

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

config_file="${CLAUDE_PLUGIN_DATA:+$CLAUDE_PLUGIN_DATA/config.env}"
templates="$here/../templates"
site_path="$HOME/agent-pages"
site_url=""
repo=""
branch="main"
name=""
force=0
while [ $# -gt 0 ]; do
  case "$1" in
    --config)    config_file="${2:?}"; shift 2 ;;
    --templates) templates="${2:?}"; shift 2 ;;
    --path)      site_path="${2:?}"; shift 2 ;;
    --site)      site_url="${2:?}"; shift 2 ;;
    --repo)      repo="${2:?}"; shift 2 ;;
    --branch)    branch="${2:?}"; shift 2 ;;
    --name)      name="${2:?}"; shift 2 ;;
    --force)     force=1; shift ;;
    -h|--help)   sed -n '2,24p' "$0"; exit 0 ;;
    *) echo "setup: unknown argument: $1" >&2; exit 1 ;;
  esac
done

say() { printf '  %s\n' "$*"; }
die() { printf 'setup: %s\n' "$*" >&2; exit 1; }
echo "agent-pages setup"

[ -n "$config_file" ] || die "--config is required (CLAUDE_PLUGIN_DATA/config.env); CLAUDE_PLUGIN_DATA not set"
templates="$(cd "$templates" 2>/dev/null && pwd || true)"
[ -n "$templates" ] && [ -d "$templates" ] || die "templates dir not found (pass --templates <CLAUDE_PLUGIN_ROOT>/templates)"
[ -n "$name" ] || name="Agent <Pages/>"

# expand a leading ~ in --path
site_path="${site_path/#\~/$HOME}"

# --- 1. scaffold the site from templates/ ---
mkdir -p "$site_path"
copy_template() {
  local f="$1" dest="$site_path/$1"
  if [ -e "$dest" ] && [ "$force" -ne 1 ]; then
    say "site    -> kept $f (exists; --force to overwrite)"
  elif [ -f "$templates/$f" ]; then
    cp "$templates/$f" "$dest"
    say "site    -> $f"
  fi
}
copy_template index.html
copy_template data.schema.json
copy_template data.json
copy_template CNAME.example

# git init + initial commit so publish.sh has a base to build on
if [ ! -d "$site_path/.git" ]; then
  git -C "$site_path" init -q
  git -C "$site_path" symbolic-ref HEAD "refs/heads/$branch" 2>/dev/null || true
  say "site    -> git init ($branch)"
fi
[ -n "$repo" ] && { git -C "$site_path" remote add origin "$repo" 2>/dev/null \
  || git -C "$site_path" remote set-url origin "$repo"; say "site    -> origin = $repo"; }
if ! git -C "$site_path" rev-parse HEAD >/dev/null 2>&1; then
  git -C "$site_path" add -A 2>/dev/null || true
  git -C "$site_path" commit -q -m "chore: scaffold agent-pages site" 2>/dev/null \
    || say "site    -> staged scaffold; make the first commit yourself (git identity unset?)"
fi

# --- 2. seed data.json metadata ---
data_json="$site_path/data.json"
if [ -f "$data_json" ] && command -v python3 >/dev/null 2>&1; then
  python3 - "$data_json" "$name" <<'PY'
import json
import sys

DEFAULT_CATEGORIES = [
    {"slug": "engineering", "label": "Engineering"},
    {"slug": "product", "label": "Product"},
    {"slug": "design", "label": "Design"},
    {"slug": "research", "label": "Research"},
    {"slug": "learning", "label": "Learning"},
    {"slug": "operations", "label": "Operations"},
    {"slug": "other", "label": "Other"},
]

path, title = sys.argv[1:3]
with open(path, "r", encoding="utf-8") as fh:
    data = json.load(fh)
site = data.setdefault("site", {})
data.setdefault("$schema", "./data.schema.json")
data.setdefault("categories", DEFAULT_CATEGORIES)
site["title"] = title
site.pop("description", None)
with open(path, "w", encoding="utf-8") as fh:
    json.dump(data, fh, ensure_ascii=False, indent=2)
    fh.write("\n")
PY
  say "site    -> data.json (title: $name)"
fi

# --- 3. write config + state to CLAUDE_PLUGIN_DATA ---
mkdir -p "$(dirname "$config_file")"
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$config_file" <<EOF
# agent-pages config + state (generated by setup.sh; edit freely)
AGENT_PAGES_PATH="$site_path"
AGENT_PAGES_REPO="$repo"
AGENT_PAGES_BRANCH="$branch"
AGENT_PAGES_SITE_BASE_URL="$site_url"
AGENT_PAGES_NAME="$name"
# state
AGENT_PAGES_SETUP_AT="$now"
EOF
say "config  -> $config_file"

cat <<EOF

Done. Your site is scaffolded at: $site_path

Next:
  - Create a GitHub repo and point the site at it:
      git -C "$site_path" remote add origin <git-url>   # if not passed via --repo
      git -C "$site_path" push -u origin $branch
  - Enable GitHub Pages (Settings > Pages > deploy from $branch / root).
  - Optional domain: cp "$site_path/CNAME.example" "$site_path/CNAME" && edit it,
    then set AGENT_PAGES_SITE_BASE_URL in $config_file for live links.
  - Generate your first page:  /agent-pages <topic>
EOF
